### ISSUE TITLE
meta-based documentation generator

### ISSUE THREAD

**Issue by krevedkokun** [HealthSamurai/macrocss#8]
- [ ] implement macro which allows to easily attach metadata to multimethod definition
- [ ] rewrite current rules using macro
- [ ] implement documentation generator which would generate hiccup based on methods metadata
- [ ] replace current documentation page with new one
